# Generated by Django 3.1.7 on 2021-04-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickburger',
            name='Message',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='pickburger',
            name='Name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
